### ISSUE TITLE
 [ Why Ibinex ] Change Font of Headers

### ISSUE THREAD

**Issue by rlbayeta** [gabrieljayhuerte/Website-Interface#7]
![image](https://user-images.githubusercontent.com/37136843/37694076-42058c7a-2d18-11e8-8865-5c259c6f73c9.png)

Change font to Montserrat

Suggested Fix
add the font in the style of header-section class

.header-section {
    font-family : "Montserrat";
}

**Comment by kevinpayas** [comment]
add the font in the style of header-section class fixed
